insert into train (model, capacity) values ('Viper RT/10', 1250);
insert into train (model, capacity) values ('Prizm', 1270);
insert into train (model, capacity) values ('Express 3500', 1799);
insert into train (model, capacity) values ('Falcon', 950);
insert into train (model, capacity) values ('Sebring', 636);
insert into train (model, capacity) values ('Rapide', 1298);
insert into train (model, capacity) values ('Bronco', 1932);
insert into train (model, capacity) values ('Omni', 1179);
insert into train (model, capacity) values ('Monte Carlo', 907);
insert into train (model, capacity) values ('LeSabre', 1977);
insert into train (model, capacity) values ('Azure T', 1201);
insert into train (model, capacity) values ('Esprit', 1243);
insert into train (model, capacity) values ('Tahoe', 697);
insert into train (model, capacity) values ('S-Series', 1168);
insert into train (model, capacity) values ('V70', 1354);
insert into train (model, capacity) values ('X6', 1598);
insert into train (model, capacity) values ('IS', 561);
insert into train (model, capacity) values ('M-Class', 1499);
insert into train (model, capacity) values ('XK Series', 1342);
insert into train (model, capacity) values ('Firebird', 1248);
insert into train (model, capacity) values ('Monte Carlo', 1150);
insert into train (model, capacity) values ('GT-R', 1023);
insert into train (model, capacity) values ('Grand Cherokee', 1764);
insert into train (model, capacity) values ('Accord', 1238);
insert into train (model, capacity) values ('Jetta', 1780);
insert into train (model, capacity) values ('Corvette', 1587);
insert into train (model, capacity) values ('Entourage', 1225);
insert into train (model, capacity) values ('944', 1245);
insert into train (model, capacity) values ('62', 937);
insert into train (model, capacity) values ('C8 Double 12 S', 692);
insert into train (model, capacity) values ('Outback Sport', 1187);
insert into train (model, capacity) values ('Corvette', 888);
insert into train (model, capacity) values ('Camaro', 1914);
insert into train (model, capacity) values ('tC', 503);
insert into train (model, capacity) values ('Sierra 3500', 1962);
insert into train (model, capacity) values ('Intrepid', 953);
insert into train (model, capacity) values ('Phantom', 774);
insert into train (model, capacity) values ('Town & Country', 1499);
insert into train (model, capacity) values ('Magnum', 1631);
insert into train (model, capacity) values ('Azera', 772);
insert into train (model, capacity) values ('Century', 744);
insert into train (model, capacity) values ('Wrangler', 1804);
insert into train (model, capacity) values ('Continental', 1516);
insert into train (model, capacity) values ('Celica', 1298);
insert into train (model, capacity) values ('Equator', 1153);
insert into train (model, capacity) values ('H2 SUV', 1279);
insert into train (model, capacity) values ('G', 716);
insert into train (model, capacity) values ('430', 1365);
insert into train (model, capacity) values ('Econoline E350', 1843);
insert into train (model, capacity) values ('Expedition', 1661);
insert into train (model, capacity) values ('G35', 906);
insert into train (model, capacity) values ('Mirage', 1044);
insert into train (model, capacity) values ('Ram Van 2500', 826);
insert into train (model, capacity) values ('F350', 1212);
insert into train (model, capacity) values ('Avalanche 1500', 1587);
insert into train (model, capacity) values ('XK Series', 1963);
insert into train (model, capacity) values ('I', 1073);
insert into train (model, capacity) values ('Matrix', 1398);
insert into train (model, capacity) values ('Savana 2500', 558);
insert into train (model, capacity) values ('S10', 1429);
insert into train (model, capacity) values ('S-Class', 568);
insert into train (model, capacity) values ('Jetta', 1477);
insert into train (model, capacity) values ('i-280', 535);
insert into train (model, capacity) values ('New Beetle', 1355);
insert into train (model, capacity) values ('Tiburon', 524);
insert into train (model, capacity) values ('Express 3500', 1269);
insert into train (model, capacity) values ('Mountaineer', 1993);
insert into train (model, capacity) values ('Vibe', 1835);
insert into train (model, capacity) values ('Grand Prix', 1238);
insert into train (model, capacity) values ('S4', 792);
insert into train (model, capacity) values ('Mazda6', 1021);
insert into train (model, capacity) values ('Grand Caravan', 606);
insert into train (model, capacity) values ('Carens', 817);
insert into train (model, capacity) values ('Vandura G1500', 1268);
insert into train (model, capacity) values ('Stealth', 687);
insert into train (model, capacity) values ('Intrepid', 1914);
insert into train (model, capacity) values ('Journey', 1572);
insert into train (model, capacity) values ('400SEL', 1901);
insert into train (model, capacity) values ('Range Rover', 1055);
insert into train (model, capacity) values ('Rio', 1377);
insert into train (model, capacity) values ('NSX', 1953);
insert into train (model, capacity) values ('Seville', 1126);
insert into train (model, capacity) values ('Express 1500', 1435);
insert into train (model, capacity) values ('Voyager', 1623);
insert into train (model, capacity) values ('E150', 830);
insert into train (model, capacity) values ('Sierra 1500', 902);
insert into train (model, capacity) values ('Continental GT', 976);
insert into train (model, capacity) values ('Protege5', 790);
insert into train (model, capacity) values ('Galant', 1822);
insert into train (model, capacity) values ('XK Series', 1850);
insert into train (model, capacity) values ('D350', 892);
insert into train (model, capacity) values ('Solstice', 1132);
insert into train (model, capacity) values ('Explorer', 1901);
insert into train (model, capacity) values ('Yukon XL 2500', 1051);
insert into train (model, capacity) values ('Azure', 1430);
insert into train (model, capacity) values ('RVR', 703);
insert into train (model, capacity) values ('Colorado', 876);
insert into train (model, capacity) values ('Diamante', 1516);
insert into train (model, capacity) values ('Fortwo', 1091);
insert into train (model, capacity) values ('Tacoma', 538);
insert into train (model, capacity) values ('Fifth Ave', 1059);
insert into train (model, capacity) values ('Lanos', 677);
insert into train (model, capacity) values ('62', 1130);
insert into train (model, capacity) values ('Coupe', 954);
insert into train (model, capacity) values ('SL-Class', 897);
insert into train (model, capacity) values ('Clubman', 1957);
insert into train (model, capacity) values ('Camry Hybrid', 701);
insert into train (model, capacity) values ('Protege5', 1935);
insert into train (model, capacity) values ('Explorer', 746);
insert into train (model, capacity) values ('Miata MX-5', 1113);
insert into train (model, capacity) values ('Challenger', 593);
insert into train (model, capacity) values ('Century', 1567);
insert into train (model, capacity) values ('Freestyle', 828);
insert into train (model, capacity) values ('XJ Series', 1795);
insert into train (model, capacity) values ('Silverado', 1094);
insert into train (model, capacity) values ('E250', 1273);
insert into train (model, capacity) values ('Accent', 1684);
insert into train (model, capacity) values ('Tundra', 1282);
insert into train (model, capacity) values ('Ram 1500 Club', 926);
insert into train (model, capacity) values ('600SEL', 1110);
insert into train (model, capacity) values ('Silhouette', 1745);
insert into train (model, capacity) values ('90', 1159);
insert into train (model, capacity) values ('Prius', 759);
insert into train (model, capacity) values ('G-Series G10', 552);
insert into train (model, capacity) values ('240SX', 1550);
insert into train (model, capacity) values ('Venza', 1664);
insert into train (model, capacity) values ('Malibu', 1381);
insert into train (model, capacity) values ('Jetta III', 705);
insert into train (model, capacity) values ('2500', 657);
insert into train (model, capacity) values ('Regal', 507);
insert into train (model, capacity) values ('SRX', 1808);
insert into train (model, capacity) values ('Ram 3500 Club', 669);
insert into train (model, capacity) values ('MDX', 1080);
insert into train (model, capacity) values ('Express 2500', 775);
insert into train (model, capacity) values ('Cooper Countryman', 1684);
insert into train (model, capacity) values ('Aerostar', 1516);
insert into train (model, capacity) values ('Tercel', 1502);
insert into train (model, capacity) values ('SL-Class', 570);
insert into train (model, capacity) values ('Seville', 1591);
insert into train (model, capacity) values ('Bonneville', 1489);
insert into train (model, capacity) values ('Fleetwood', 1733);
insert into train (model, capacity) values ('Parisienne', 1936);
insert into train (model, capacity) values ('Paseo', 786);
insert into train (model, capacity) values ('Legacy', 1778);
insert into train (model, capacity) values ('Mazdaspeed 3', 589);
insert into train (model, capacity) values ('IS', 733);
insert into train (model, capacity) values ('CR-V', 567);
insert into train (model, capacity) values ('S-Class', 709);
insert into train (model, capacity) values ('G', 752);
insert into train (model, capacity) values ('Passat', 1033);
insert into train (model, capacity) values ('Forester', 1709);
insert into train (model, capacity) values ('Exige', 1825);
insert into train (model, capacity) values ('Uplander', 1578);
insert into train (model, capacity) values ('Monte Carlo', 882);
insert into train (model, capacity) values ('Allroad', 1024);
insert into train (model, capacity) values ('Wrangler', 953);
insert into train (model, capacity) values ('Express 2500', 665);
insert into train (model, capacity) values ('Santa Fe', 604);
insert into train (model, capacity) values ('New Yorker', 1988);
insert into train (model, capacity) values ('S10', 501);
insert into train (model, capacity) values ('XJ Series', 1901);
insert into train (model, capacity) values ('Corvette', 1396);
insert into train (model, capacity) values ('300', 785);
insert into train (model, capacity) values ('Cordia', 912);
insert into train (model, capacity) values ('G37', 906);
insert into train (model, capacity) values ('Grand Marquis', 1924);
insert into train (model, capacity) values ('Sentra', 1487);
insert into train (model, capacity) values ('H2', 1931);
insert into train (model, capacity) values ('Eclipse', 846);
insert into train (model, capacity) values ('Caravan', 1404);
insert into train (model, capacity) values ('ES', 684);
insert into train (model, capacity) values ('Elantra', 1146);
insert into train (model, capacity) values ('D150', 1484);
insert into train (model, capacity) values ('Type 2', 1304);
insert into train (model, capacity) values ('1 Series', 1374);
insert into train (model, capacity) values ('M', 1210);
insert into train (model, capacity) values ('X-90', 1589);
insert into train (model, capacity) values ('Pajero', 1474);
insert into train (model, capacity) values ('Envoy', 507);
insert into train (model, capacity) values ('Cougar', 940);
insert into train (model, capacity) values ('Classic', 1854);
insert into train (model, capacity) values ('Silverado 2500', 1706);
insert into train (model, capacity) values ('GTO', 1234);
insert into train (model, capacity) values ('Continental GT', 1402);
insert into train (model, capacity) values ('Malibu', 996);
insert into train (model, capacity) values ('Carens', 798);
insert into train (model, capacity) values ('Transit Connect', 1473);
insert into train (model, capacity) values ('Courier', 1669);
insert into train (model, capacity) values ('RX Hybrid', 1942);
insert into train (model, capacity) values ('Express 3500', 1145);
insert into train (model, capacity) values ('F-350 Super Duty', 1057);
insert into train (model, capacity) values ('Pilot', 1961);
insert into train (model, capacity) values ('Cayenne', 1897);
insert into train (model, capacity) values ('Ram 2500 Club', 1937);
insert into train (model, capacity) values ('Laser', 570);
insert into train (model, capacity) values ('Swift', 1665);
insert into train (model, capacity) values ('Firebird Trans Am', 1652);
insert into train (model, capacity) values ('G', 1925);
insert into train (model, capacity) values ('F150', 1538);
insert into train (model, capacity) values ('Solara', 1965);
insert into train (model, capacity) values ('Lumina', 1758);
insert into train (model, capacity) values ('928', 843);
insert into train (model, capacity) values ('T100', 898);
insert into train (model, capacity) values ('Tahoe', 1182);
insert into train (model, capacity) values ('164', 589);
insert into train (model, capacity) values ('C70', 1359);
insert into train (model, capacity) values ('Accord', 799);
insert into train (model, capacity) values ('Club Wagon', 1108);
insert into train (model, capacity) values ('Continental', 713);
insert into train (model, capacity) values ('FR-S', 1201);
insert into train (model, capacity) values ('Bonneville', 837);
insert into train (model, capacity) values ('Mirage', 1074);
insert into train (model, capacity) values ('XL-7', 1842);
insert into train (model, capacity) values ('599 GTB Fiorano', 1823);
insert into train (model, capacity) values ('98', 1295);
insert into train (model, capacity) values ('Grand Vitara', 558);
insert into train (model, capacity) values ('Celica', 545);
insert into train (model, capacity) values ('GTO', 1703);
insert into train (model, capacity) values ('Safari', 1607);
insert into train (model, capacity) values ('2500 Club Coupe', 1910);
insert into train (model, capacity) values ('S40', 1787);
insert into train (model, capacity) values ('Pathfinder Armada', 1089);
insert into train (model, capacity) values ('Fox', 1014);
insert into train (model, capacity) values ('Raider', 1335);
insert into train (model, capacity) values ('Sebring', 1331);
insert into train (model, capacity) values ('Park Avenue', 678);
insert into train (model, capacity) values ('Sixty Special', 576);
insert into train (model, capacity) values ('Amanti', 710);
insert into train (model, capacity) values ('Festiva', 785);
insert into train (model, capacity) values ('Sentra', 1735);
insert into train (model, capacity) values ('Cavalier', 1912);
insert into train (model, capacity) values ('Continental', 573);
insert into train (model, capacity) values ('Sonata', 1153);
insert into train (model, capacity) values ('Highlander', 1776);
insert into train (model, capacity) values ('Pajero', 817);
insert into train (model, capacity) values ('Cooper', 718);
insert into train (model, capacity) values ('Yukon XL 1500', 1382);
insert into train (model, capacity) values ('Fiesta', 1583);
insert into train (model, capacity) values ('Forester', 763);
insert into train (model, capacity) values ('Mountaineer', 1605);
insert into train (model, capacity) values ('98', 1677);
insert into train (model, capacity) values ('Alero', 1719);
insert into train (model, capacity) values ('Sienna', 1915);
insert into train (model, capacity) values ('Yukon XL 2500', 508);
insert into train (model, capacity) values ('Explorer Sport Trac', 1745);
insert into train (model, capacity) values ('Bel Air', 558);
insert into train (model, capacity) values ('2500 Club Coupe', 1152);
insert into train (model, capacity) values ('LeSabre', 1581);
insert into train (model, capacity) values ('E-Series', 1875);
insert into train (model, capacity) values ('Express', 1767);
insert into train (model, capacity) values ('S6', 925);
insert into train (model, capacity) values ('Tundra', 674);
insert into train (model, capacity) values ('Discovery', 811);
insert into train (model, capacity) values ('MX-6', 718);
insert into train (model, capacity) values ('Tribute', 959);
insert into train (model, capacity) values ('Tacoma', 1546);
insert into train (model, capacity) values ('ES', 550);
insert into train (model, capacity) values ('Coupe GT', 1605);
insert into train (model, capacity) values ('QX', 831);
insert into train (model, capacity) values ('RSX', 691);
insert into train (model, capacity) values ('R32', 944);
insert into train (model, capacity) values ('F350', 1697);
insert into train (model, capacity) values ('Vandura 3500', 1353);
insert into train (model, capacity) values ('Silverado 1500', 729);
insert into train (model, capacity) values ('Grand Voyager', 1615);
insert into train (model, capacity) values ('S40', 798);
insert into train (model, capacity) values ('Escalade', 763);
insert into train (model, capacity) values ('Crown Victoria', 1230);
insert into train (model, capacity) values ('Ion', 1040);
insert into train (model, capacity) values ('Milan', 727);
insert into train (model, capacity) values ('Grand Voyager', 1035);
insert into train (model, capacity) values ('Excel', 1543);
insert into train (model, capacity) values ('Silverado 2500', 1760);
insert into train (model, capacity) values ('Tahoe', 734);
insert into train (model, capacity) values ('626', 1658);
insert into train (model, capacity) values ('Forte', 516);
insert into train (model, capacity) values ('Tacoma', 872);
insert into train (model, capacity) values ('A6', 1310);
insert into train (model, capacity) values ('X6 M', 1485);
insert into train (model, capacity) values ('Yukon XL 1500', 1024);
insert into train (model, capacity) values ('XF', 541);
insert into train (model, capacity) values ('RL', 1023);
insert into train (model, capacity) values ('GTI', 1317);
insert into train (model, capacity) values ('L300', 985);
insert into train (model, capacity) values ('Mystique', 995);
insert into train (model, capacity) values ('Expedition', 571);
insert into train (model, capacity) values ('F-Series', 992);
insert into train (model, capacity) values ('Z4 M', 1174);
insert into train (model, capacity) values ('Freelander', 1210);
insert into train (model, capacity) values ('Tahoe', 868);
insert into train (model, capacity) values ('Forester', 1590);
insert into train (model, capacity) values ('S-Type', 1237);
insert into train (model, capacity) values ('Tucson', 531);
insert into train (model, capacity) values ('Country', 617);
insert into train (model, capacity) values ('Regal', 1596);
insert into train (model, capacity) values ('Precis', 1407);
insert into train (model, capacity) values ('Diablo', 559);
insert into train (model, capacity) values ('Range Rover', 954);
insert into train (model, capacity) values ('Silverado 3500', 1393);
insert into train (model, capacity) values ('57', 1442);
insert into train (model, capacity) values ('Vantage', 1091);
insert into train (model, capacity) values ('VS Commodore', 1655);
insert into train (model, capacity) values ('3500', 1944);
insert into train (model, capacity) values ('Golf', 1087);
insert into train (model, capacity) values ('B-Series', 1786);
insert into train (model, capacity) values ('Continental Super', 711);
insert into train (model, capacity) values ('Contour', 1973);
insert into train (model, capacity) values ('Corvette', 552);
insert into train (model, capacity) values ('Titan', 1728);
insert into train (model, capacity) values ('Bonneville', 714);
insert into train (model, capacity) values ('F150', 1522);
insert into train (model, capacity) values ('Suburban 2500', 1852);
insert into train (model, capacity) values ('Impreza', 1254);
insert into train (model, capacity) values ('Freestyle', 770);
insert into train (model, capacity) values ('Montero Sport', 756);
insert into train (model, capacity) values ('Festiva', 553);
insert into train (model, capacity) values ('XJ', 1348);
insert into train (model, capacity) values ('HS', 745);
insert into train (model, capacity) values ('Tribeca', 1113);
insert into train (model, capacity) values ('Horizon', 1810);
insert into train (model, capacity) values ('Concorde', 511);
insert into train (model, capacity) values ('F150', 1266);
insert into train (model, capacity) values ('Riviera', 1337);
insert into train (model, capacity) values ('Sierra 3500', 808);
insert into train (model, capacity) values ('Civic', 590);
insert into train (model, capacity) values ('Santa Fe', 785);
insert into train (model, capacity) values ('Montero Sport', 1059);
insert into train (model, capacity) values ('RDX', 1763);
insert into train (model, capacity) values ('MX-6', 1271);
insert into train (model, capacity) values ('Savana 3500', 1719);
insert into train (model, capacity) values ('Savana 3500', 747);
insert into train (model, capacity) values ('Viper', 1061);
insert into train (model, capacity) values ('Thunderbird', 749);
insert into train (model, capacity) values ('RX', 646);
insert into train (model, capacity) values ('Suburban', 1332);
insert into train (model, capacity) values ('Expedition', 505);
insert into train (model, capacity) values ('Voyager', 964);
insert into train (model, capacity) values ('Mirage', 1756);
insert into train (model, capacity) values ('Virage', 1395);
insert into train (model, capacity) values ('Express 1500', 852);
insert into train (model, capacity) values ('Park Avenue', 790);
insert into train (model, capacity) values ('Sonoma', 829);
insert into train (model, capacity) values ('SL-Class', 1887);
insert into train (model, capacity) values ('Bonneville', 1450);
insert into train (model, capacity) values ('A4', 1131);
insert into train (model, capacity) values ('RAV4', 1368);
insert into train (model, capacity) values ('Integra', 1421);
insert into train (model, capacity) values ('Sierra 2500', 1584);
insert into train (model, capacity) values ('Quattroporte', 1586);
insert into train (model, capacity) values ('Sportvan G30', 967);
insert into train (model, capacity) values ('Camaro', 1626);
insert into train (model, capacity) values ('Spectra', 1209);
insert into train (model, capacity) values ('GT500', 1905);
insert into train (model, capacity) values ('Achieva', 1281);
insert into train (model, capacity) values ('Express 1500', 916);
insert into train (model, capacity) values ('Armada', 1349);
insert into train (model, capacity) values ('Colorado', 1030);
insert into train (model, capacity) values ('E350', 1996);
insert into train (model, capacity) values ('STS', 1688);
insert into train (model, capacity) values ('Outback', 951);
insert into train (model, capacity) values ('MDX', 1190);
insert into train (model, capacity) values ('Bronco', 1149);
insert into train (model, capacity) values ('GS', 637);
insert into train (model, capacity) values ('Paseo', 1644);
insert into train (model, capacity) values ('Blazer', 736);
insert into train (model, capacity) values ('Land Cruiser', 1098);
insert into train (model, capacity) values ('Fleetwood', 1924);
insert into train (model, capacity) values ('Diamante', 567);
insert into train (model, capacity) values ('S10 Blazer', 1622);
insert into train (model, capacity) values ('Charger', 912);
insert into train (model, capacity) values ('Sienna', 1960);
insert into train (model, capacity) values ('Montero', 1723);
insert into train (model, capacity) values ('Legacy', 545);
insert into train (model, capacity) values ('C-Class', 894);
insert into train (model, capacity) values ('Murano', 1467);
insert into train (model, capacity) values ('Camry Hybrid', 796);
insert into train (model, capacity) values ('RL', 1790);
insert into train (model, capacity) values ('Space', 1859);
insert into train (model, capacity) values ('5 Series', 1713);
insert into train (model, capacity) values ('Spirit', 1127);
insert into train (model, capacity) values ('Savana 2500', 1661);
insert into train (model, capacity) values ('Sportage', 813);
insert into train (model, capacity) values ('Regal', 687);
insert into train (model, capacity) values ('M6', 1611);
insert into train (model, capacity) values ('Cabriolet', 1638);
insert into train (model, capacity) values ('Integra', 1608);
insert into train (model, capacity) values ('Camaro', 879);
insert into train (model, capacity) values ('Esprit', 1188);
insert into train (model, capacity) values ('3 Series', 1597);
insert into train (model, capacity) values ('Grand Prix', 1619);
insert into train (model, capacity) values ('Crown Victoria', 1028);
insert into train (model, capacity) values ('57', 1502);
insert into train (model, capacity) values ('Ram 2500', 986);
insert into train (model, capacity) values ('I', 699);
insert into train (model, capacity) values ('Mark VII', 749);
insert into train (model, capacity) values ('325', 743);
insert into train (model, capacity) values ('3500 Club Coupe', 883);
insert into train (model, capacity) values ('1500', 834);
insert into train (model, capacity) values ('C8', 1773);
insert into train (model, capacity) values ('330', 758);
insert into train (model, capacity) values ('PT Cruiser', 1440);
insert into train (model, capacity) values ('Land Cruiser', 852);
insert into train (model, capacity) values ('Fusion', 1314);
insert into train (model, capacity) values ('Corvair', 1253);
insert into train (model, capacity) values ('Town Car', 773);
insert into train (model, capacity) values ('Boxster', 711);
insert into train (model, capacity) values ('Dakota Club', 1533);
insert into train (model, capacity) values ('R8', 1386);
insert into train (model, capacity) values ('5000CS Quattro', 730);
insert into train (model, capacity) values ('Avalanche 2500', 622);
insert into train (model, capacity) values ('Titan', 1856);
insert into train (model, capacity) values ('Grand Cherokee', 1393);
insert into train (model, capacity) values ('Accord', 1222);
insert into train (model, capacity) values ('3500', 688);
insert into train (model, capacity) values ('300', 1843);
insert into train (model, capacity) values ('Pathfinder', 1344);
insert into train (model, capacity) values ('Spectra5', 1507);
insert into train (model, capacity) values ('5 Series', 1929);
insert into train (model, capacity) values ('Town Car', 764);
insert into train (model, capacity) values ('3000GT', 1985);
insert into train (model, capacity) values ('Colorado', 764);
insert into train (model, capacity) values ('Sunbird', 1023);
insert into train (model, capacity) values ('Silverado 1500', 1840);
insert into train (model, capacity) values ('Fiesta', 1134);
insert into train (model, capacity) values ('Explorer Sport Trac', 1479);
insert into train (model, capacity) values ('Firebird', 723);
insert into train (model, capacity) values ('4Runner', 1049);
insert into train (model, capacity) values ('CTS', 1710);
insert into train (model, capacity) values ('Ram Van 2500', 1024);
insert into train (model, capacity) values ('Silverado 2500', 1249);
insert into train (model, capacity) values ('Escort', 501);
insert into train (model, capacity) values ('TundraMax', 1595);
insert into train (model, capacity) values ('SL-Class', 680);
insert into train (model, capacity) values ('900', 1630);
insert into train (model, capacity) values ('Marquis', 1759);
insert into train (model, capacity) values ('Sienna', 691);
insert into train (model, capacity) values ('Colt', 720);
insert into train (model, capacity) values ('Odyssey', 864);
insert into train (model, capacity) values ('PT Cruiser', 941);
insert into train (model, capacity) values ('Yukon Denali', 1890);
insert into train (model, capacity) values ('Tahoe', 1477);
insert into train (model, capacity) values ('XT', 986);
insert into train (model, capacity) values ('M6', 1356);
insert into train (model, capacity) values ('530', 1984);
insert into train (model, capacity) values ('2500', 1804);
insert into train (model, capacity) values ('80', 1470);
insert into train (model, capacity) values ('B9 Tribeca', 528);
insert into train (model, capacity) values ('LS', 1292);
insert into train (model, capacity) values ('XC70', 1766);
insert into train (model, capacity) values ('911', 1570);
insert into train (model, capacity) values ('Torrent', 1497);
insert into train (model, capacity) values ('Bravada', 832);
insert into train (model, capacity) values ('Yukon XL 1500', 587);
insert into train (model, capacity) values ('Sonata', 1275);
insert into train (model, capacity) values ('Safari', 1495);
insert into train (model, capacity) values ('Legacy', 1015);
insert into train (model, capacity) values ('Econoline E250', 1784);
insert into train (model, capacity) values ('Pathfinder', 1875);
insert into train (model, capacity) values ('XLR', 1980);
insert into train (model, capacity) values ('Maxima', 1516);
insert into train (model, capacity) values ('9-3', 637);
insert into train (model, capacity) values ('Caprice Classic', 1189);
insert into train (model, capacity) values ('Monte Carlo', 1319);
insert into train (model, capacity) values ('Z4', 727);
insert into train (model, capacity) values ('Rendezvous', 1404);
insert into train (model, capacity) values ('Talon', 1737);
insert into train (model, capacity) values ('Bonneville', 1279);
insert into train (model, capacity) values ('I', 719);
insert into train (model, capacity) values ('Armada', 1494);
insert into train (model, capacity) values ('Excel', 950);
insert into train (model, capacity) values ('Fairlane', 1216);
insert into train (model, capacity) values ('Bronco II', 1373);
insert into train (model, capacity) values ('Previa', 1641);
insert into train (model, capacity) values ('Sienna', 571);
insert into train (model, capacity) values ('CTS', 1636);
insert into train (model, capacity) values ('Sequoia', 1487);
insert into train (model, capacity) values ('Town Car', 1643);
insert into train (model, capacity) values ('Sportage', 1108);
insert into train (model, capacity) values ('LeSabre', 988);
insert into train (model, capacity) values ('DeVille', 906);
insert into train (model, capacity) values ('E-Series', 1545);
insert into train (model, capacity) values ('SL-Class', 1604);
insert into train (model, capacity) values ('Fiesta', 1905);
insert into train (model, capacity) values ('Grand Prix', 1986);
insert into train (model, capacity) values ('Sonata', 692);
insert into train (model, capacity) values ('Fifth Ave', 1581);
insert into train (model, capacity) values ('Odyssey', 842);
insert into train (model, capacity) values ('Cayenne', 1251);
insert into train (model, capacity) values ('T100 Xtra', 1021);
insert into train (model, capacity) values ('Fox', 1926);
insert into train (model, capacity) values ('Entourage', 1532);
insert into train (model, capacity) values ('Suburban 1500', 1180);
insert into train (model, capacity) values ('Edge', 1364);
insert into train (model, capacity) values ('Neon', 1580);
insert into train (model, capacity) values ('QX', 1904);
insert into train (model, capacity) values ('Tacoma', 1186);
insert into train (model, capacity) values ('Grand Prix', 881);
insert into train (model, capacity) values ('Vibe', 1248);
insert into train (model, capacity) values ('Catera', 988);
insert into train (model, capacity) values ('Defender 110', 1906);
insert into train (model, capacity) values ('968', 1027);
insert into train (model, capacity) values ('Sonoma Club Coupe', 951);
insert into train (model, capacity) values ('7 Series', 1245);
insert into train (model, capacity) values ('Firebird', 1924);
insert into train (model, capacity) values ('Supra', 1828);
insert into train (model, capacity) values ('944', 1152);
insert into train (model, capacity) values ('GTO', 1644);
insert into train (model, capacity) values ('Astro', 1560);
insert into train (model, capacity) values ('7 Series', 1751);
insert into train (model, capacity) values ('Hombre Space', 1822);
insert into train (model, capacity) values ('Explorer', 972);
insert into train (model, capacity) values ('Fox', 1710);
insert into train (model, capacity) values ('A4', 962);
insert into train (model, capacity) values ('612 Scaglietti', 1100);
insert into train (model, capacity) values ('Accord', 1437);
insert into train (model, capacity) values ('Protege5', 925);
insert into train (model, capacity) values ('Suburban 2500', 1554);
insert into train (model, capacity) values ('Carrera GT', 1978);
insert into train (model, capacity) values ('FR-S', 1967);
insert into train (model, capacity) values ('Suburban 1500', 739);
insert into train (model, capacity) values ('California', 1312);
insert into train (model, capacity) values ('Previa', 855);
insert into train (model, capacity) values ('940', 1318);
insert into train (model, capacity) values ('9000', 1234);
insert into train (model, capacity) values ('E-Class', 799);
insert into train (model, capacity) values ('B-Series Plus', 779);
insert into train (model, capacity) values ('Range Rover', 1320);
insert into train (model, capacity) values ('C70', 1876);
insert into train (model, capacity) values ('Maxima', 878);
insert into train (model, capacity) values ('Yaris', 1917);
insert into train (model, capacity) values ('CLK-Class', 852);
insert into train (model, capacity) values ('Suburban 2500', 553);
insert into train (model, capacity) values ('B-Series', 517);
insert into train (model, capacity) values ('SLS-Class', 991);
insert into train (model, capacity) values ('Express 1500', 1162);
insert into train (model, capacity) values ('Savana 3500', 539);
insert into train (model, capacity) values ('E350', 1389);
insert into train (model, capacity) values ('Festiva', 1085);
insert into train (model, capacity) values ('Gallardo', 1852);
insert into train (model, capacity) values ('QX', 697);
insert into train (model, capacity) values ('RX-7', 985);
insert into train (model, capacity) values ('Boxster', 1012);
insert into train (model, capacity) values ('Regal', 538);
insert into train (model, capacity) values ('QX', 705);
insert into train (model, capacity) values ('Malibu', 1782);
insert into train (model, capacity) values ('Avenger', 1662);
insert into train (model, capacity) values ('H2', 690);
insert into train (model, capacity) values ('Tundra', 1884);
insert into train (model, capacity) values ('Savana 3500', 1140);
insert into train (model, capacity) values ('FX', 681);
insert into train (model, capacity) values ('E-Series', 954);
insert into train (model, capacity) values ('62', 1234);
insert into train (model, capacity) values ('E-Series', 882);
insert into train (model, capacity) values ('MX-5', 1956);
insert into train (model, capacity) values ('Town Car', 509);
insert into train (model, capacity) values ('Aura', 708);
insert into train (model, capacity) values ('Xterra', 1276);
insert into train (model, capacity) values ('Jetta', 1777);
insert into train (model, capacity) values ('Swift', 1077);
insert into train (model, capacity) values ('XC90', 850);
insert into train (model, capacity) values ('XG350', 764);
insert into train (model, capacity) values ('RX-7', 1578);
insert into train (model, capacity) values ('SLS-Class', 1479);
insert into train (model, capacity) values ('Exige', 1725);
insert into train (model, capacity) values ('DeVille', 1104);
insert into train (model, capacity) values ('V50', 900);
insert into train (model, capacity) values ('3500 Club Coupe', 1588);
insert into train (model, capacity) values ('929', 700);
insert into train (model, capacity) values ('Phantom', 542);
insert into train (model, capacity) values ('I', 901);
insert into train (model, capacity) values ('Passat', 1680);
insert into train (model, capacity) values ('Grand Vitara', 1335);
insert into train (model, capacity) values ('Express 2500', 1707);
insert into train (model, capacity) values ('Type 2', 1071);
insert into train (model, capacity) values ('Sonoma', 1155);
insert into train (model, capacity) values ('Blazer', 1473);
insert into train (model, capacity) values ('Hombre', 1913);
insert into train (model, capacity) values ('CT', 1470);
insert into train (model, capacity) values ('LaCrosse', 520);
insert into train (model, capacity) values ('Millenia', 799);
insert into train (model, capacity) values ('323', 1083);
insert into train (model, capacity) values ('Savana 3500', 1239);
insert into train (model, capacity) values ('Passport', 832);
insert into train (model, capacity) values ('Express 3500', 1677);
insert into train (model, capacity) values ('Avalanche 1500', 1281);
insert into train (model, capacity) values ('Pajero', 1746);
insert into train (model, capacity) values ('B-Series', 1356);
insert into train (model, capacity) values ('Viper', 1745);
insert into train (model, capacity) values ('Cayenne', 1179);
insert into train (model, capacity) values ('Navigator', 891);
insert into train (model, capacity) values ('TL', 848);
insert into train (model, capacity) values ('Maxima', 1900);
insert into train (model, capacity) values ('500', 950);
insert into train (model, capacity) values ('SVX', 956);
insert into train (model, capacity) values ('Murciélago', 1177);
insert into train (model, capacity) values ('6000', 1006);
insert into train (model, capacity) values ('LeMans', 606);
insert into train (model, capacity) values ('S10', 769);
insert into train (model, capacity) values ('Econoline E150', 1313);
insert into train (model, capacity) values ('T100', 857);
insert into train (model, capacity) values ('Golf', 1145);
insert into train (model, capacity) values ('CX-7', 622);
insert into train (model, capacity) values ('IS-F', 1901);
insert into train (model, capacity) values ('Tundra', 1160);
insert into train (model, capacity) values ('Genesis', 1231);
insert into train (model, capacity) values ('Insight', 839);
insert into train (model, capacity) values ('M3', 820);
insert into train (model, capacity) values ('S6', 651);
insert into train (model, capacity) values ('Taurus', 547);
insert into train (model, capacity) values ('Fiero', 1950);
insert into train (model, capacity) values ('7 Series', 1631);
insert into train (model, capacity) values ('Quest', 1382);
insert into train (model, capacity) values ('Continental', 770);
insert into train (model, capacity) values ('R32', 1304);
insert into train (model, capacity) values ('Intrepid', 1492);
insert into train (model, capacity) values ('Taurus X', 1152);
insert into train (model, capacity) values ('MX-5', 623);
insert into train (model, capacity) values ('STS', 1759);
insert into train (model, capacity) values ('XJ Series', 1358);
insert into train (model, capacity) values ('X3', 561);
insert into train (model, capacity) values ('F350', 567);
insert into train (model, capacity) values ('Corvette', 623);
insert into train (model, capacity) values ('Camaro', 597);
insert into train (model, capacity) values ('Legacy', 827);
insert into train (model, capacity) values ('M3', 1795);
insert into train (model, capacity) values ('F-Series', 568);
insert into train (model, capacity) values ('C/V', 1578);
insert into train (model, capacity) values ('Intrepid', 1323);
insert into train (model, capacity) values ('Equator', 1267);
insert into train (model, capacity) values ('Cougar', 1318);
insert into train (model, capacity) values ('Golf', 1825);
insert into train (model, capacity) values ('Civic', 1396);
insert into train (model, capacity) values ('RVR', 1821);
insert into train (model, capacity) values ('3500', 1767);
insert into train (model, capacity) values ('Club Wagon', 1683);
insert into train (model, capacity) values ('Cordia', 1262);
insert into train (model, capacity) values ('ZX2', 1108);
insert into train (model, capacity) values ('Murano', 1161);
insert into train (model, capacity) values ('Courier', 977);
insert into train (model, capacity) values ('Type 2', 822);
insert into train (model, capacity) values ('Impala SS', 1093);
insert into train (model, capacity) values ('TT', 1902);
insert into train (model, capacity) values ('LeSabre', 1351);
insert into train (model, capacity) values ('612 Scaglietti', 998);
insert into train (model, capacity) values ('S4', 573);
insert into train (model, capacity) values ('SLS-Class', 640);
insert into train (model, capacity) values ('Prizm', 567);
insert into train (model, capacity) values ('Yukon', 568);
insert into train (model, capacity) values ('Sigma', 1810);
insert into train (model, capacity) values ('F350', 1440);
insert into train (model, capacity) values ('88', 1650);
insert into train (model, capacity) values ('300', 1557);
insert into train (model, capacity) values ('G35', 838);
insert into train (model, capacity) values ('M', 935);
insert into train (model, capacity) values ('RDX', 1453);
insert into train (model, capacity) values ('LTD Crown Victoria', 625);
insert into train (model, capacity) values ('Express 2500', 1673);
insert into train (model, capacity) values ('Ram 1500', 704);
insert into train (model, capacity) values ('Sonata', 788);
insert into train (model, capacity) values ('GL-Class', 1098);
insert into train (model, capacity) values ('Range Rover', 634);
insert into train (model, capacity) values ('Genesis', 1469);
insert into train (model, capacity) values ('Taurus', 1569);
insert into train (model, capacity) values ('Civic', 1887);
insert into train (model, capacity) values ('HS', 1600);
insert into train (model, capacity) values ('Excel', 1661);
insert into train (model, capacity) values ('A6', 567);
insert into train (model, capacity) values ('Eldorado', 1716);
insert into train (model, capacity) values ('Rogue', 1748);
insert into train (model, capacity) values ('Camaro', 861);
insert into train (model, capacity) values ('3 Series', 701);
insert into train (model, capacity) values ('F150', 1835);
insert into train (model, capacity) values ('Sierra 2500', 824);
insert into train (model, capacity) values ('Cooper Countryman', 1960);
insert into train (model, capacity) values ('Esprit', 1955);
insert into train (model, capacity) values ('900', 995);
insert into train (model, capacity) values ('Escort', 1287);
insert into train (model, capacity) values ('Accent', 1421);
insert into train (model, capacity) values ('Golf', 1146);
insert into train (model, capacity) values ('Ram 3500', 1965);
insert into train (model, capacity) values ('929', 1253);
insert into train (model, capacity) values ('Aspire', 1187);
insert into train (model, capacity) values ('Camaro', 514);
insert into train (model, capacity) values ('Galant', 838);
insert into train (model, capacity) values ('Thunderbird', 555);
insert into train (model, capacity) values ('Chariot', 567);
insert into train (model, capacity) values ('Econoline E250', 1178);
insert into train (model, capacity) values ('Titan', 810);
insert into train (model, capacity) values ('Grand Cherokee', 1864);
insert into train (model, capacity) values ('CT', 1901);
insert into train (model, capacity) values ('Bronco II', 1719);
insert into train (model, capacity) values ('Edge', 1349);
insert into train (model, capacity) values ('Ranger', 888);
insert into train (model, capacity) values ('F150', 1688);
insert into train (model, capacity) values ('Express 2500', 1880);
insert into train (model, capacity) values ('Titan', 1863);
insert into train (model, capacity) values ('Outback', 1237);
insert into train (model, capacity) values ('CX-7', 1568);
insert into train (model, capacity) values ('Montero', 1115);
insert into train (model, capacity) values ('Z4', 1548);
insert into train (model, capacity) values ('Familia', 1295);
insert into train (model, capacity) values ('V50', 1917);
insert into train (model, capacity) values ('TT', 875);
insert into train (model, capacity) values ('Outlander', 881);
insert into train (model, capacity) values ('LeSabre', 954);
insert into train (model, capacity) values ('Continental', 1824);
insert into train (model, capacity) values ('Aveo', 1060);
insert into train (model, capacity) values ('B-Series', 1556);
insert into train (model, capacity) values ('Astro', 744);
insert into train (model, capacity) values ('Reventón', 1633);
insert into train (model, capacity) values ('Verona', 1298);
insert into train (model, capacity) values ('Passat', 834);
insert into train (model, capacity) values ('300SE', 929);
insert into train (model, capacity) values ('Torrent', 1852);
insert into train (model, capacity) values ('Sable', 1264);
insert into train (model, capacity) values ('Gallardo', 620);
insert into train (model, capacity) values ('Blazer', 1177);
insert into train (model, capacity) values ('SVX', 1960);
insert into train (model, capacity) values ('7 Series', 1084);
insert into train (model, capacity) values ('Accord', 934);
insert into train (model, capacity) values ('SL-Class', 911);
insert into train (model, capacity) values ('FX', 1634);
insert into train (model, capacity) values ('Prowler', 1975);
insert into train (model, capacity) values ('FX', 1816);
insert into train (model, capacity) values ('Compass', 1904);
insert into train (model, capacity) values ('4Runner', 677);
insert into train (model, capacity) values ('Ram Van 1500', 1926);
insert into train (model, capacity) values ('Eclipse', 1890);
insert into train (model, capacity) values ('Econoline E350', 1977);
insert into train (model, capacity) values ('Trans Sport', 1952);
insert into train (model, capacity) values ('Corvette', 688);
insert into train (model, capacity) values ('4Runner', 1293);
insert into train (model, capacity) values ('Passat', 1828);
insert into train (model, capacity) values ('X5', 547);
insert into train (model, capacity) values ('F150', 1777);
insert into train (model, capacity) values ('Town & Country', 1832);
insert into train (model, capacity) values ('Grand Marquis', 627);
insert into train (model, capacity) values ('RX', 899);
insert into train (model, capacity) values ('Turbo Firefly', 559);
insert into train (model, capacity) values ('Intrepid', 1988);
insert into train (model, capacity) values ('Marquis', 970);
insert into train (model, capacity) values ('Forenza', 821);
insert into train (model, capacity) values ('LeSabre', 656);
insert into train (model, capacity) values ('MX-5', 1978);
insert into train (model, capacity) values ('Eclipse', 1423);
insert into train (model, capacity) values ('Ram 1500', 1138);
insert into train (model, capacity) values ('Caravan', 532);
insert into train (model, capacity) values ('Tacoma', 1655);
insert into train (model, capacity) values ('GTI', 997);
insert into train (model, capacity) values ('Pilot', 1137);
insert into train (model, capacity) values ('Tahoe', 1677);
insert into train (model, capacity) values ('Elise', 1549);
insert into train (model, capacity) values ('90', 1754);
insert into train (model, capacity) values ('300M', 1749);
insert into train (model, capacity) values ('Xterra', 910);
insert into train (model, capacity) values ('Sonoma', 1382);
insert into train (model, capacity) values ('Corvette', 1038);
insert into train (model, capacity) values ('Accent', 773);
insert into train (model, capacity) values ('626', 1395);
insert into train (model, capacity) values ('Corvette', 1284);
insert into train (model, capacity) values ('1500 Club Coupe', 1170);
insert into train (model, capacity) values ('GTI', 1166);
insert into train (model, capacity) values ('7 Series', 874);
insert into train (model, capacity) values ('Mustang', 1651);
insert into train (model, capacity) values ('GTO', 1595);
insert into train (model, capacity) values ('Ram Wagon B150', 1907);
insert into train (model, capacity) values ('LX', 1031);
insert into train (model, capacity) values ('Swift', 1221);
insert into train (model, capacity) values ('Bonneville', 1368);
insert into train (model, capacity) values ('E250', 695);
insert into train (model, capacity) values ('Q', 558);
insert into train (model, capacity) values ('960', 1553);
insert into train (model, capacity) values ('Stratus', 567);
insert into train (model, capacity) values ('Continental Super', 1174);
insert into train (model, capacity) values ('Pilot', 1126);
insert into train (model, capacity) values ('CL-Class', 549);
insert into train (model, capacity) values ('B-Series', 1323);
insert into train (model, capacity) values ('Silverado 3500', 1156);
insert into train (model, capacity) values ('X5', 870);
insert into train (model, capacity) values ('Carrera GT', 733);
insert into train (model, capacity) values ('Grand Caravan', 1975);
insert into train (model, capacity) values ('Diamante', 1150);
insert into train (model, capacity) values ('Corvette', 692);
insert into train (model, capacity) values ('Eos', 542);
insert into train (model, capacity) values ('Grand Caravan', 1970);
insert into train (model, capacity) values ('Avalanche', 1973);
insert into train (model, capacity) values ('Caprice', 582);
insert into train (model, capacity) values ('Blazer', 528);
insert into train (model, capacity) values ('C-Class', 1261);
insert into train (model, capacity) values ('T100', 1107);
insert into train (model, capacity) values ('Mariner', 559);
insert into train (model, capacity) values ('E-Class', 1574);
insert into train (model, capacity) values ('Thunderbird', 1936);
insert into train (model, capacity) values ('S-Class', 1206);
insert into train (model, capacity) values ('RX', 772);
insert into train (model, capacity) values ('Stratus', 703);
insert into train (model, capacity) values ('S-Type', 557);
insert into train (model, capacity) values ('Savana', 1140);
insert into train (model, capacity) values ('Somerset', 1745);
insert into train (model, capacity) values ('5000CS', 1433);
insert into train (model, capacity) values ('Challenger', 866);
insert into train (model, capacity) values ('Mazdaspeed 3', 575);
insert into train (model, capacity) values ('DBS', 1797);
insert into train (model, capacity) values ('Xterra', 820);
insert into train (model, capacity) values ('Mazdaspeed 3', 1823);
insert into train (model, capacity) values ('Galant', 586);
insert into train (model, capacity) values ('Ram 2500', 1048);
insert into train (model, capacity) values ('Seville', 1489);
insert into train (model, capacity) values ('Fiero', 1175);
insert into train (model, capacity) values ('940', 1855);
insert into train (model, capacity) values ('M', 1689);
insert into train (model, capacity) values ('Sonata', 1420);
insert into train (model, capacity) values ('Escape', 1633);
insert into train (model, capacity) values ('Focus', 1322);
insert into train (model, capacity) values ('Stratus', 972);
insert into train (model, capacity) values ('Avalanche', 538);
insert into train (model, capacity) values ('Montero Sport', 1076);
insert into train (model, capacity) values ('Regal', 661);
insert into train (model, capacity) values ('Edge', 670);
insert into train (model, capacity) values ('Sportage', 821);
insert into train (model, capacity) values ('SLR McLaren', 1899);
insert into train (model, capacity) values ('Sable', 989);
insert into train (model, capacity) values ('Laser', 1032);
insert into train (model, capacity) values ('MKX', 542);
insert into train (model, capacity) values ('Range Rover', 1987);
insert into train (model, capacity) values ('4000s', 562);
insert into train (model, capacity) values ('Taurus', 1125);
insert into train (model, capacity) values ('Club Wagon', 1400);
insert into train (model, capacity) values ('Swift', 1857);
insert into train (model, capacity) values ('Mazda6', 767);
insert into train (model, capacity) values ('GX', 957);
insert into train (model, capacity) values ('Laser', 835);
insert into train (model, capacity) values ('Aerio', 771);
insert into train (model, capacity) values ('Grand Cherokee', 1435);
insert into train (model, capacity) values ('Bonneville', 1314);
insert into train (model, capacity) values ('Ram Van 3500', 835);
insert into train (model, capacity) values ('Econoline E350', 1098);
insert into train (model, capacity) values ('Odyssey', 1388);
insert into train (model, capacity) values ('Suburban 1500', 1061);
insert into train (model, capacity) values ('Corvette', 1773);
insert into train (model, capacity) values ('Pathfinder', 1989);
insert into train (model, capacity) values ('Equinox', 505);
insert into train (model, capacity) values ('Yukon', 1841);
insert into train (model, capacity) values ('CX-9', 1681);
insert into train (model, capacity) values ('Cougar', 1299);
insert into train (model, capacity) values ('S5', 1202);
insert into train (model, capacity) values ('S90', 1353);
insert into train (model, capacity) values ('Eclipse', 1056);
insert into train (model, capacity) values ('Civic', 1491);
insert into train (model, capacity) values ('Town Car', 1245);
insert into train (model, capacity) values ('Continental', 1781);
insert into train (model, capacity) values ('626', 918);
insert into train (model, capacity) values ('Mirage', 720);
insert into train (model, capacity) values ('SLX', 1996);
insert into train (model, capacity) values ('Lancer Evolution', 801);
insert into train (model, capacity) values ('H1', 1939);
insert into train (model, capacity) values ('E350', 935);
insert into train (model, capacity) values ('Compass', 1148);
insert into train (model, capacity) values ('Impreza', 1513);
insert into train (model, capacity) values ('CR-V', 1224);
insert into train (model, capacity) values ('Yukon XL 1500', 806);
insert into train (model, capacity) values ('Aspen', 1503);
insert into train (model, capacity) values ('Altima', 1008);
insert into train (model, capacity) values ('Golf', 557);
insert into train (model, capacity) values ('Quest', 1386);
insert into train (model, capacity) values ('Crown Victoria', 1346);
insert into train (model, capacity) values ('Miata MX-5', 1699);
insert into train (model, capacity) values ('Prius', 1290);
insert into train (model, capacity) values ('NX', 1836);
insert into train (model, capacity) values ('911', 553);
insert into train (model, capacity) values ('IS', 1308);
insert into train (model, capacity) values ('Ram 1500', 1381);
insert into train (model, capacity) values ('525', 1802);
insert into train (model, capacity) values ('Justy', 634);
insert into train (model, capacity) values ('Typ-1', 1693);
insert into train (model, capacity) values ('TSX', 1907);
insert into train (model, capacity) values ('Legacy', 1058);
insert into train (model, capacity) values ('FX', 1542);
insert into train (model, capacity) values ('Milan', 1497);
insert into train (model, capacity) values ('Expedition', 1216);
insert into train (model, capacity) values ('X5', 1401);
insert into train (model, capacity) values ('S10 Blazer', 856);
insert into train (model, capacity) values ('Suburban 1500', 516);
insert into train (model, capacity) values ('Camaro', 628);
insert into train (model, capacity) values ('Navigator L', 1154);
insert into train (model, capacity) values ('TT', 1247);
insert into train (model, capacity) values ('Grand Vitara', 737);
insert into train (model, capacity) values ('Escalade EXT', 1906);
insert into train (model, capacity) values ('Eclipse', 899);
insert into train (model, capacity) values ('B-Series Plus', 765);
insert into train (model, capacity) values ('Tahoe', 1014);
insert into train (model, capacity) values ('RAV4', 1386);
insert into train (model, capacity) values ('Expedition EL', 623);
insert into train (model, capacity) values ('S-Series', 669);
insert into train (model, capacity) values ('Viper', 819);
insert into train (model, capacity) values ('Cutlass', 611);
insert into train (model, capacity) values ('Regal', 1484);
insert into train (model, capacity) values ('Quest', 542);
insert into train (model, capacity) values ('Grand Voyager', 727);
insert into train (model, capacity) values ('M5', 1456);
insert into train (model, capacity) values ('Golf III', 1175);
insert into train (model, capacity) values ('Tribute', 808);
insert into train (model, capacity) values ('Century', 1437);
insert into train (model, capacity) values ('960', 1758);
insert into train (model, capacity) values ('Stratus', 1879);
insert into train (model, capacity) values ('Grand Marquis', 849);
insert into train (model, capacity) values ('Venture', 890);
insert into train (model, capacity) values ('Xtra', 1948);
insert into train (model, capacity) values ('GTI', 1772);
insert into train (model, capacity) values ('Tacoma', 824);
insert into train (model, capacity) values ('Relay', 1468);
insert into train (model, capacity) values ('Journey', 1338);
insert into train (model, capacity) values ('Firebird', 812);
insert into train (model, capacity) values ('Familia', 1159);
insert into train (model, capacity) values ('911', 1367);
insert into train (model, capacity) values ('RL', 617);
insert into train (model, capacity) values ('Leone', 828);
insert into train (model, capacity) values ('Passat', 1438);
insert into train (model, capacity) values ('Mark LT', 842);
insert into train (model, capacity) values ('Dakota Club', 849);
insert into train (model, capacity) values ('LeSabre', 1428);
insert into train (model, capacity) values ('Hombre Space', 726);
insert into train (model, capacity) values ('Yukon', 1711);
insert into train (model, capacity) values ('Q', 1802);
insert into train (model, capacity) values ('Panamera', 858);
insert into train (model, capacity) values ('Envoy', 1526);
insert into train (model, capacity) values ('xD', 1618);
insert into train (model, capacity) values ('A5', 1174);
insert into train (model, capacity) values ('X6 M', 1345);
insert into train (model, capacity) values ('W201', 986);
insert into train (model, capacity) values ('Cherokee', 816);
insert into train (model, capacity) values ('100', 1653);
insert into train (model, capacity) values ('Murciélago', 642);
insert into train (model, capacity) values ('Continental Flying Spur', 1008);
insert into train (model, capacity) values ('Talon', 899);
insert into train (model, capacity) values ('Mazda6', 1771);
insert into train (model, capacity) values ('Pajero', 1599);
insert into train (model, capacity) values ('LS', 1749);
insert into train (model, capacity) values ('Savana 2500', 1823);
insert into train (model, capacity) values ('Mountaineer', 733);
insert into train (model, capacity) values ('F150', 1877);
insert into train (model, capacity) values ('Mustang', 1413);
insert into train (model, capacity) values ('Express 3500', 1024);
insert into train (model, capacity) values ('T100', 1089);
insert into train (model, capacity) values ('V50', 1479);
insert into train (model, capacity) values ('Enclave', 1394);
insert into train (model, capacity) values ('S80', 1086);
insert into train (model, capacity) values ('Bonneville', 661);
insert into train (model, capacity) values ('Maxima', 1790);
insert into train (model, capacity) values ('Lucerne', 1536);
insert into train (model, capacity) values ('Tribute', 1750);
insert into train (model, capacity) values ('Corolla', 1607);
insert into train (model, capacity) values ('LS', 1152);
insert into train (model, capacity) values ('Justy', 1134);
insert into train (model, capacity) values ('Range Rover Sport', 1438);
insert into train (model, capacity) values ('Q7', 1989);
insert into train (model, capacity) values ('Thunderbird', 1701);
insert into train (model, capacity) values ('Caliber', 726);
insert into train (model, capacity) values ('Sienna', 992);
insert into train (model, capacity) values ('Element', 1494);
insert into train (model, capacity) values ('Golf', 1303);
insert into train (model, capacity) values ('Datsun/Nissan Z-car', 1860);
insert into train (model, capacity) values ('Endeavor', 1610);
insert into train (model, capacity) values ('Silverado 2500', 1642);
insert into train (model, capacity) values ('Tundra', 767);
insert into train (model, capacity) values ('Mustang', 1550);
insert into train (model, capacity) values ('Outback', 560);
insert into train (model, capacity) values ('SVX', 1994);
insert into train (model, capacity) values ('Riviera', 1647);
insert into train (model, capacity) values ('S6', 701);
insert into train (model, capacity) values ('1500 Club Coupe', 1159);
insert into train (model, capacity) values ('Explorer', 743);
insert into train (model, capacity) values ('Ranger', 1012);
insert into train (model, capacity) values ('Lancer Evolution', 776);
insert into train (model, capacity) values ('Avalon', 1126);
insert into train (model, capacity) values ('Spirit', 1613);
insert into train (model, capacity) values ('F250', 546);
insert into train (model, capacity) values ('EX', 1340);
insert into train (model, capacity) values ('Festiva', 1935);
insert into train (model, capacity) values ('F450', 1930);
insert into train (model, capacity) values ('Galaxie', 1271);
insert into train (model, capacity) values ('Ascender', 1405);
insert into train (model, capacity) values ('ES', 1378);
insert into train (model, capacity) values ('CLS-Class', 850);
insert into train (model, capacity) values ('SLX', 584);
insert into train (model, capacity) values ('Grand Prix', 765);
insert into train (model, capacity) values ('Protege5', 722);
insert into train (model, capacity) values ('Patriot', 1180);
insert into train (model, capacity) values ('S-Series', 642);
insert into train (model, capacity) values ('Edge', 826);
insert into train (model, capacity) values ('Eldorado', 1910);
insert into train (model, capacity) values ('GX', 1181);
insert into train (model, capacity) values ('Uplander', 1016);
insert into train (model, capacity) values ('H3', 1632);
insert into train (model, capacity) values ('Frontier', 860);
insert into train (model, capacity) values ('Electra', 1245);
insert into train (model, capacity) values ('Altima', 925);
insert into train (model, capacity) values ('599 GTB Fiorano', 566);
insert into train (model, capacity) values ('MPV', 879);
insert into train (model, capacity) values ('CR-V', 1946);
